# ---------------------------------------------
# General
# ---------------------------------------------

# True color
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# Start windows/panes in the current directory
bind c new-window -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Allow mouse use
set -g mouse on

# ---------------------------------------------
# Windows 
# ---------------------------------------------

# Window numbering
set -g base-index 1
setw -g pane-base-index 1

# Next/previous window
bind n next-window
bind p previous-window

# Rename window
bind , command-prompt -p "Rename window:" "rename-window '%%'"

# Automatically renumber windows when one is closed
set -g renumber-windows on

# ---------------------------------------------
# Copy mode 
# ---------------------------------------------

setw -g mode-keys vi
set -s set-clipboard on

# Vim-style copy mode selection
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# ---------------------------------------------
# Plugins 
# ---------------------------------------------

# TPM Plugin
set -g @plugin 'tmux-plugins/tpm'

# List of plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

# Resurrect and continuum
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-save-interval '15'

# Themes
set -g @plugin 'jimeh/tmux-themepack'
# set -g @themepack 'powerline/block/gray'
set -g @plugin 'uhs-robert/tmux-oasis'
set -g @oasis_mode_format "icon"
set -g @oasis_flavor "abyss_dark"
set -g @oasis_dim_inactive "off"
set -g @oasis_session_icon ""
set -g @oasis_folder_icon ""

# NOTE: Keep at bottom
# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
